fix: workers need to run migrate & collectstatic too
currently failing at startup with
> ValueError: Missing staticfiles manifest entry for 'images/favicons/favicon.ico'

a follow-up change will adjust the ECS task definition to use this new script.

https://new-hippo.atlassian.net/browse/HC-31